### PR TITLE
Mr. Integration

### LINKED ISSUE #56: Map Roulette Integration
### Context

At the moment one can export data and create a new MR task with it. We should integrate against the latest MR API and allow task creation from MLEnabler

### Actions

- [ ] Convert JS MR code to python from conflation work
- [ ] Add `integrations` table for storing API integrations
- [ ] Add UI to export page

cc/ @martham93

### PR DESCRIPTION
**Pull request by ingalls**
### Context

Add the ability to push inferences to a given integration

Screenshot from 2020-08-14 13-07-37

### Actions

- [ ] Add UI for exporting integrations

cc/ @martham93

### CODE REVIEW

**Comment by ingalls** [comment]
Screenshot from 2020-08-14 13-19-50

**Comment by ingalls** [comment]
Screenshot from 2020-08-17 08-24-40

**Comment by ingalls** [comment]
Screenshot from 2020-08-18 10-09-06

**Review by martham93 — APPROVED** [review]
awesome work! looks good to merge 
cc @ingalls

**Pull request merged**
