### PR TITLE
Automated Inference Generation

### PR DESCRIPTION
**Pull request by ingalls**
## Context

Now that MLEnabler is able to build and store ECS images in the ECR, as well as to store Image API locations, this PR adds the ability to do the following:
- Spin up a custom inference stack (Chip-N-Scale Like)
- Send and track chips being run against the inference stack
- Save inferences directly to the MLEnabler DB
- Destroy the stack upon inference completion

This PR will migrate and heavily modify the [Chip-N-scale](https://github.com/developmentseed/chip-n-scale-queue-arranger) to live inside the MLEnabler project.

## Tasks
- [x] Export values from main stack required by substack to facilitate resource sharing
- [x] Create CF Template for creating a prediction ECS task/service
- [x] Add chip-n-scale lambda build to MLEnabler
- [x] Add Lambda to prediction CF Template
- [x] Create UI for creating stack and generating chip lists
- [x] ... more to come ...

cc/ @martham93 @Geoyi @geohacker

### CODE REVIEW

**Comment by ingalls** [comment]
A few screenshots of the new Prediction component

Screenshot from 2020-03-24 08-15-44
Screenshot from 2020-03-24 08-15-32
Screenshot from 2020-03-24 08-15-27
Screenshot from 2020-03-24 08-15-24

**Comment by ingalls** [comment]
Screenshot from 2020-03-24 12-35-12
Screenshot from 2020-03-24 12-35-06

**Comment by ingalls** [comment]
Screenshot from 2020-03-24 12-48-02

**Comment by martham93** [comment]
this all looks awesome!! Thank you for all of your hard work, so excited to try these out. 
cc @ingalls

**Comment by geohacker** [comment]
@ingalls !!!!!!!!!!!!!!! this is looking spectacular. Thank you! Can we all get a demo sometime?

**Comment by ingalls** [comment]
Screenshot from 2020-03-26 11-18-02

**Comment by ingalls** [comment]
Ok going to sign off, TODO tomorrow:

- [ ] Investigate why tiletanic is only producing 4 tiles for large geometries at z18 (is it only picking up corners?!)
- [x] SQS=>Lambda works (:tada:), but lambda fails to actually do anything useful (unsurprising since I haven't touched this code other than stealing it from chip-n-scale)

Screenshot from 2020-03-26 19-03-30

**Comment by ingalls** [comment]
Screenshot from 2020-03-30 08-16-34

**Comment by martham93** [comment]
the option of having the imagery selection panel is nice. Would it be possible for a user to specify a tile end point? Some projects get specific imagery end points that couldn't always be listed as an option. 
cc @ingalls

**Comment by ingalls** [comment]
@martham93 yes, that was in a previous PR. You add imagery sources via the Models panel. This lists the imagery sources that have been added to a model

**Pull request merged**
